import type { Metadata } from "next";
import { Geist, Geist_Mono,Orbitron,Lora,Raleway } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron  = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "LAGAGUE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} ${lora.variable} ${raleway.variable} antialiased`}
      >
        <div className="bg-linear-to-br from-green-900 via-black to-green-900">
          <Header />
        {children}
        <Footer/>
        </div>
      </body>
    </html>
  );
}
